# Generated by Django 2.2.14 on 2022-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('reorder_level', models.BooleanField(default=False)),
            ],
        ),
    ]
