# Generated by Django 2.2.14 on 2022-03-22 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(max_length=100)),
                ('item_id', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('STORE', 'STORE'), ('LORRY', 'LORRY'), ('PICK_UP', 'PICK_UP'), ('VAN', 'VAN'), ('WHOLESALE', 'WHOLESALE')], default='STORE', max_length=20)),
                ('discount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 18, 4, 22, 923225))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
